# coding: utf-8

"""
    Firecracker API

    RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. The transport medium is a Unix Domain Socket.  # noqa: E501

    OpenAPI spec version: 0.23.0
    Contact: compute-capsule@amazon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BalloonUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'amount_mb': 'int'
    }

    attribute_map = {
        'amount_mb': 'amount_mb'
    }

    def __init__(self, amount_mb=None):  # noqa: E501
        """BalloonUpdate - a model defined in Swagger"""  # noqa: E501
        self._amount_mb = None
        self.discriminator = None
        self.amount_mb = amount_mb

    @property
    def amount_mb(self):
        """Gets the amount_mb of this BalloonUpdate.  # noqa: E501

        Target balloon size in MB.  # noqa: E501

        :return: The amount_mb of this BalloonUpdate.  # noqa: E501
        :rtype: int
        """
        return self._amount_mb

    @amount_mb.setter
    def amount_mb(self, amount_mb):
        """Sets the amount_mb of this BalloonUpdate.

        Target balloon size in MB.  # noqa: E501

        :param amount_mb: The amount_mb of this BalloonUpdate.  # noqa: E501
        :type: int
        """
        if amount_mb is None:
            raise ValueError("Invalid value for `amount_mb`, must not be `None`")  # noqa: E501

        self._amount_mb = amount_mb

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BalloonUpdate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BalloonUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
