# coding: utf-8

"""
    Firecracker API

    RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. The transport medium is a Unix Domain Socket.  # noqa: E501

    OpenAPI spec version: 0.23.0
    Contact: compute-capsule@amazon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_snapshot(self):
        """Test case for create_snapshot

        Creates a full or diff snapshot. Post-boot only.  # noqa: E501
        """
        pass

    def test_create_sync_action(self):
        """Test case for create_sync_action

        Creates a synchronous action.  # noqa: E501
        """
        pass

    def test_describe_balloon_config(self):
        """Test case for describe_balloon_config

        Returns the current balloon device configuration.  # noqa: E501
        """
        pass

    def test_describe_balloon_stats(self):
        """Test case for describe_balloon_stats

        Returns the latest balloon device statistics, only if enabled pre-boot.  # noqa: E501
        """
        pass

    def test_describe_instance(self):
        """Test case for describe_instance

        Returns general information about an instance.  # noqa: E501
        """
        pass

    def test_get_machine_configuration(self):
        """Test case for get_machine_configuration

        Gets the machine configuration of the VM.  # noqa: E501
        """
        pass

    def test_load_snapshot(self):
        """Test case for load_snapshot

        Loads a snapshot. Pre-boot only.  # noqa: E501
        """
        pass

    def test_mmds_config_put(self):
        """Test case for mmds_config_put

        Set MMDS configuration. Pre-boot only.  # noqa: E501
        """
        pass

    def test_mmds_get(self):
        """Test case for mmds_get

        Get the MMDS data store.  # noqa: E501
        """
        pass

    def test_mmds_patch(self):
        """Test case for mmds_patch

        Updates the MMDS data store.  # noqa: E501
        """
        pass

    def test_mmds_put(self):
        """Test case for mmds_put

        Creates a MMDS (Microvm Metadata Service) data store.  # noqa: E501
        """
        pass

    def test_patch_balloon(self):
        """Test case for patch_balloon

        Updates a balloon device.  # noqa: E501
        """
        pass

    def test_patch_balloon_stats_interval(self):
        """Test case for patch_balloon_stats_interval

        Updates a balloon device statistics polling interval.  # noqa: E501
        """
        pass

    def test_patch_guest_drive_by_id(self):
        """Test case for patch_guest_drive_by_id

        Updates the properties of a drive. Post-boot only.  # noqa: E501
        """
        pass

    def test_patch_guest_network_interface_by_id(self):
        """Test case for patch_guest_network_interface_by_id

        Updates the rate limiters applied to a network interface. Post-boot only.  # noqa: E501
        """
        pass

    def test_patch_machine_configuration(self):
        """Test case for patch_machine_configuration

        Partially updates the Machine Configuration of the VM. Pre-boot only.  # noqa: E501
        """
        pass

    def test_patch_vm(self):
        """Test case for patch_vm

        Updates the microVM state.  # noqa: E501
        """
        pass

    def test_put_balloon(self):
        """Test case for put_balloon

        Creates or updates a balloon device.  # noqa: E501
        """
        pass

    def test_put_guest_boot_source(self):
        """Test case for put_guest_boot_source

        Creates or updates the boot source. Pre-boot only.  # noqa: E501
        """
        pass

    def test_put_guest_drive_by_id(self):
        """Test case for put_guest_drive_by_id

        Creates or updates a drive. Pre-boot only.  # noqa: E501
        """
        pass

    def test_put_guest_network_interface_by_id(self):
        """Test case for put_guest_network_interface_by_id

        Creates a network interface. Pre-boot only.  # noqa: E501
        """
        pass

    def test_put_guest_vsock(self):
        """Test case for put_guest_vsock

        Creates/updates a vsock device. Pre-boot only.  # noqa: E501
        """
        pass

    def test_put_logger(self):
        """Test case for put_logger

        Initializes the logger by specifying a named pipe or a file for the logs output.  # noqa: E501
        """
        pass

    def test_put_machine_configuration(self):
        """Test case for put_machine_configuration

        Updates the Machine Configuration of the VM. Pre-boot only.  # noqa: E501
        """
        pass

    def test_put_metrics(self):
        """Test case for put_metrics

        Initializes the metrics system by specifying a named pipe or a file for the metrics output.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
