# coding: utf-8

# flake8: noqa
"""
    Firecracker API

    RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. The transport medium is a Unix Domain Socket.  # noqa: E501

    OpenAPI spec version: 0.23.0
    Contact: compute-capsule@amazon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.balloon import Balloon
from swagger_client.models.balloon_stats import BalloonStats
from swagger_client.models.balloon_stats_update import BalloonStatsUpdate
from swagger_client.models.balloon_update import BalloonUpdate
from swagger_client.models.boot_source import BootSource
from swagger_client.models.cpu_template import CpuTemplate
from swagger_client.models.drive import Drive
from swagger_client.models.error import Error
from swagger_client.models.instance_action_info import InstanceActionInfo
from swagger_client.models.instance_info import InstanceInfo
from swagger_client.models.logger import Logger
from swagger_client.models.machine_configuration import MachineConfiguration
from swagger_client.models.metrics import Metrics
from swagger_client.models.mmds_config import MmdsConfig
from swagger_client.models.network_interface import NetworkInterface
from swagger_client.models.partial_drive import PartialDrive
from swagger_client.models.partial_network_interface import PartialNetworkInterface
from swagger_client.models.rate_limiter import RateLimiter
from swagger_client.models.snapshot_create_params import SnapshotCreateParams
from swagger_client.models.snapshot_load_params import SnapshotLoadParams
from swagger_client.models.token_bucket import TokenBucket
from swagger_client.models.vm import Vm
from swagger_client.models.vsock import Vsock
